# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

# Kings of Leon
Artist.create([
  {
    name: "Kings of Leon",
    genre: "Alternative/Indie, Rock",
    bio: "Kings of Leon is an American rock band formed in Mount Juliet, Tennessee, in 1999. The band includes brothers Caleb, Nathan, and Jared Followill and their cousin Matthew Followill.",
    image_url: "https://i.scdn.co/image/ab6761610000e5eb6fc940f2e99875ced9bafed0",
  },
  {
    name: "Fontaines D.C.",
    genre: "Post-Punk, Rock",
    bio: "Fontaines D.C. is an Irish post-punk band formed in Dublin in 2017. They have gained acclaim for their energetic performances and sharp, poetic lyrics.",
    image_url: "https://media.pitchfork.com/photos/671ff8f08b6b29b326c1869e/2:1/w_2560%2Cc_limit/Fontaines-DC.jpg",
  },
  {
    name: "Arctic Monkeys",
    genre: "Indie Rock, Alternative",
    bio: "Arctic Monkeys are an English rock band formed in Sheffield in 2002. Known for their sharp lyrics and evolving musical style, they are considered one of the best bands of their generation.",
    image_url: "https://i.scdn.co/image/ab6761610000e5eb7da39dea0a72f581535fb11f",
  },
  {
    name: "The Strokes",
    genre: "Indie Rock, Garage Rock",
    bio: "The Strokes are an American rock band formed in New York City in 1998. Their debut album \"Is This It\" revolutionized the garage rock revival.",
    image_url: "https://static01.nyt.com/images/2020/04/16/arts/13strokes-review1/13strokes-review1-videoSixteenByNineJumbo1600.jpg",
  },
  {
    name: "The Killers",
    genre: "Alternative Rock, Indie",
    bio: "The Killers are an American rock band formed in Las Vegas in 2001. They are known for their anthemic hits and energetic performances.",
    image_url: "https://i.scdn.co/image/ab6761610000e5eb207b21f3ed0ee96adce3166a",
  },
  {
    name: "Tame Impala",
    genre: "Psychedelic Rock, Indie",
    bio: "Tame Impala is the project of Australian multi-instrumentalist Kevin Parker. Known for blending psychedelic rock with modern pop and electronic elements.",
    image_url: "https://i1.sndcdn.com/avatars-yHA8nds2mqg4uYtr-kyxTzw-t1080x1080.jpg",
  },
  {
    name: "The Black Keys",
    genre: "Blues Rock, Garage Rock",
    bio: "The Black Keys are an American rock duo formed in Akron, Ohio, in 2001. They gained widespread acclaim for their raw, blues-infused rock sound.",
    image_url: "https://i.scdn.co/image/ab6761610000e5eb12a6369237c73c25794b6ed9",
  },
  {
    name: "Foals",
    genre: "Indie Rock, Alternative",
    bio: "Foals are an English rock band formed in Oxford in 2005. Known for their intricate guitar work and energetic live performances.",
    image_url: "https://i.scdn.co/image/ab6761610000e5eb5f0109249ffd70b2d85a9467",
  },
  {
    name: "Vampire Weekend",
    genre: "Indie Rock, Baroque Pop",
    bio: "Vampire Weekend is an American rock band formed in New York City in 2006. Their unique sound blends indie rock with elements of world music and pop.",
    image_url: "https://www.rollingstone.com/wp-content/uploads/2018/06/vampire-weekend-debut-album-abcc4ca0-a4df-4c7b-95ca-ad447c4142d2.jpg?w=910&h=511&crop=1",
  },
  {
    name: "Interpol",
    genre: "Post-Punk Revival, Rock",
    bio: "Interpol is an American rock band formed in New York City in 1997. Their dark, atmospheric sound helped define the post-punk revival.",
    image_url: "https://i.guim.co.uk/img/media/0c7d6d4c3d45d85aa06368201f2439e2b2c8f7ce/0_329_1667_1000/master/1667.jpg?width=1200&quality=85&auto=format&fit=max&s=0ac73713adca904b8d3322d6622153ef",
  },
  {
    name: "Cage The Elephant",
    genre: "Alternative Rock, Indie",
    bio: "Cage the Elephant is an American rock band from Bowling Green, Kentucky, formed in 2006. Known for their eclectic sound and energetic live performances, they achieved widespread success with songs like \"Ain't No Rest for the Wicked\" and \"Come a Little Closer.\"",
    image_url: "https://media.npr.org/assets/img/2019/04/26/cge_neilkrug_wide-c64f6bdf0eba6ba4bf0d1bed8370680fceb54207.jpg",
  },
])

Concert.create([
  { artist_id: 1, date: "September 26, 2024", venue: "Bridgestone Arena", city: "Nashville, TN" },
  { artist_id: 1, date: "October 3, 2024", venue: "Madison Square Garden", city: "New York, NY" },
  { artist_id: 1, date: "November 10, 2024", venue: "Red Rocks Amphitheatre", city: "Morrison, CO" },
  { artist_id: 1, date: "November 20, 2024", venue: "The Forum", city: "Los Angeles, CA" },
  { artist_id: 1, date: "December 5, 2024", venue: "Wembley Arena", city: "London, England" },
  { artist_id: 1, date: "December 15, 2024", venue: "O2 Arena", city: "London, England" },
  { artist_id: 1, date: "January 10, 2025", venue: "Scotiabank Arena", city: "Toronto, Canada" },
  { artist_id: 1, date: "February 20, 2025", venue: "United Center", city: "Chicago, IL" },
  { artist_id: 1, date: "March 15, 2025", venue: "Barclays Center", city: "Brooklyn, NY" },
  { artist_id: 1, date: "April 25, 2025", venue: "TD Garden", city: "Boston, MA" },

  { artist_id: 2, date: "December 7, 2024", venue: "3Arena", city: "Dublin, Ireland" },
  { artist_id: 2, date: "November 22, 2024", venue: "Alexandra Palace", city: "London, England" },
  { artist_id: 2, date: "October 10, 2024", venue: "Barrowland Ballroom", city: "Glasgow, Scotland" },
  { artist_id: 2, date: "September 18, 2024", venue: "O2 Academy", city: "Birmingham, England" },
  { artist_id: 2, date: "August 20, 2024", venue: "Royal Albert Hall", city: "London, England" },
  { artist_id: 2, date: "July 15, 2024", venue: "Olympia Theatre", city: "Dublin, Ireland" },
  { artist_id: 2, date: "June 25, 2024", venue: "The SSE Arena", city: "Belfast, Northern Ireland" },
  { artist_id: 2, date: "May 30, 2024", venue: "O2 Academy Brixton", city: "London, England" },
  { artist_id: 2, date: "April 22, 2024", venue: "First Direct Arena", city: "Leeds, England" },
  { artist_id: 2, date: "March 10, 2024", venue: "Manchester Arena", city: "Manchester, England" },

  { artist_id: 3, date: "October 1, 2023", venue: "Kia Forum", city: "Inglewood, CA" },
  { artist_id: 3, date: "October 6, 2023", venue: "Foro Sol", city: "Mexico City, Mexico" },
  { artist_id: 3, date: "September 15, 2023", venue: "The O2", city: "London, England" },
  { artist_id: 3, date: "August 20, 2023", venue: "Madison Square Garden", city: "New York, NY" },
  { artist_id: 3, date: "July 18, 2023", venue: "Hollywood Bowl", city: "Los Angeles, CA" },
  { artist_id: 3, date: "June 22, 2023", venue: "Red Rocks Amphitheatre", city: "Morrison, CO" },
  { artist_id: 3, date: "May 10, 2023", venue: "Coachella", city: "Indio, CA" },
  { artist_id: 3, date: "April 15, 2023", venue: "Glastonbury Festival", city: "Somerset, England" },
  { artist_id: 3, date: "March 20, 2023", venue: "Rogers Arena", city: "Vancouver, Canada" },
  { artist_id: 3, date: "February 28, 2023", venue: "United Center", city: "Chicago, IL" },

  { artist_id: 4, date: "March 19, 2022", venue: "Lollapalooza Argentina", city: "San Isidro, Argentina" },
  { artist_id: 4, date: "August 27, 2011", venue: "Reading Festival", city: "Reading, England" },
  { artist_id: 4, date: "July 15, 2022", venue: "The Roxy", city: "Los Angeles, CA" },
  { artist_id: 4, date: "June 20, 2022", venue: "Hollywood Bowl", city: "Los Angeles, CA" },
  { artist_id: 4, date: "May 18, 2022", venue: "Red Rocks Amphitheatre", city: "Morrison, CO" },
  { artist_id: 4, date: "April 25, 2022", venue: "Coachella", city: "Indio, CA" },
  { artist_id: 4, date: "March 15, 2022", venue: "Madison Square Garden", city: "New York, NY" },
  { artist_id: 4, date: "February 10, 2022", venue: "Barclays Center", city: "Brooklyn, NY" },
  { artist_id: 4, date: "January 22, 2022", venue: "The Forum", city: "Los Angeles, CA" },
  { artist_id: 4, date: "December 5, 2021", venue: "Scotiabank Arena", city: "Toronto, Canada" },

  { artist_id: 5, date: "December 22, 2013", venue: "Wembley Stadium", city: "London, England" },
  { artist_id: 5, date: "July 5, 2009", venue: "Royal Albert Hall", city: "London, England" },
  { artist_id: 5, date: "June 15, 2010", venue: "Madison Square Garden", city: "New York, NY" },
  { artist_id: 5, date: "May 20, 2010", venue: "The Cosmopolitan", city: "Las Vegas, NV" },
  { artist_id: 5, date: "April 25, 2010", venue: "Red Rocks Amphitheatre", city: "Morrison, CO" },
  { artist_id: 5, date: "March 18, 2010", venue: "Hollywood Bowl", city: "Los Angeles, CA" },
  { artist_id: 5, date: "February 28, 2010", venue: "The O2", city: "London, England" },
  { artist_id: 5, date: "January 15, 2010", venue: "Coachella", city: "Indio, CA" },
  { artist_id: 5, date: "December 10, 2009", venue: "Glastonbury Festival", city: "Somerset, England" },
  { artist_id: 5, date: "November 15, 2009", venue: "United Center", city: "Chicago, IL" },

  { artist_id: 6, date: "April 13, 2019", venue: "Coachella", city: "Indio, CA" },
  { artist_id: 6, date: "March 19, 2022", venue: "Wells Fargo Center", city: "Philadelphia, PA" },
  { artist_id: 6, date: "February 25, 2022", venue: "Scotiabank Arena", city: "Toronto, Canada" },
  { artist_id: 6, date: "January 15, 2022", venue: "TD Garden", city: "Boston, MA" },
  { artist_id: 6, date: "December 10, 2021", venue: "United Center", city: "Chicago, IL" },
  { artist_id: 6, date: "November 5, 2021", venue: "Madison Square Garden", city: "New York, NY" },
  { artist_id: 6, date: "October 1, 2021", venue: "Red Rocks Amphitheatre", city: "Morrison, CO" },
  { artist_id: 6, date: "September 15, 2021", venue: "Hollywood Bowl", city: "Los Angeles, CA" },
  { artist_id: 6, date: "August 10, 2021", venue: "The O2", city: "London, England" },
  { artist_id: 6, date: "July 5, 2021", venue: "Olympia Theatre", city: "Dublin, Ireland" },

  { artist_id: 7, date: "May 15, 2024", venue: "Co-op Live", city: "Manchester, England" },
  { artist_id: 7, date: "November 2, 2023", venue: "Hollywood Bowl", city: "Los Angeles, CA" },
  { artist_id: 7, date: "October 5, 2023", venue: "Red Rocks Amphitheatre", city: "Morrison, CO" },
  { artist_id: 7, date: "September 12, 2023", venue: "United Center", city: "Chicago, IL" },
  { artist_id: 7, date: "August 10, 2023", venue: "Madison Square Garden", city: "New York, NY" },
  { artist_id: 7, date: "July 15, 2023", venue: "TD Garden", city: "Boston, MA" },
  { artist_id: 7, date: "June 20, 2023", venue: "Scotiabank Arena", city: "Toronto, Canada" },
  { artist_id: 7, date: "May 25, 2023", venue: "The Forum", city: "Los Angeles, CA" },
  { artist_id: 7, date: "April 10, 2023", venue: "Barclays Center", city: "Brooklyn, NY" },
  { artist_id: 7, date: "March 5, 2023", venue: "O2 Arena", city: "London, England" },

  { artist_id: 8, date: "May 15, 2024", venue: "Co-op Live", city: "Manchester, England" },
  { artist_id: 8, date: "November 2, 2023", venue: "Hollywood Bowl", city: "Los Angeles, CA" },
  { artist_id: 8, date: "October 5, 2023", venue: "Red Rocks Amphitheatre", city: "Morrison, CO" },
  { artist_id: 8, date: "September 12, 2023", venue: "United Center", city: "Chicago, IL" },
  { artist_id: 8, date: "August 10, 2023", venue: "Madison Square Garden", city: "New York, NY" },
  { artist_id: 8, date: "July 15, 2023", venue: "TD Garden", city: "Boston, MA" },
  { artist_id: 8, date: "June 20, 2023", venue: "Scotiabank Arena", city: "Toronto, Canada" },
  { artist_id: 8, date: "May 25, 2023", venue: "The Forum", city: "Los Angeles, CA" },
  { artist_id: 8, date: "April 10, 2023", venue: "Barclays Center", city: "Brooklyn, NY" },
  { artist_id: 8, date: "March 5, 2023", venue: "O2 Arena", city: "London, England" },

  { artist_id: 9, date: "April 13, 2019", venue: "Coachella", city: "Indio, CA" },
  { artist_id: 9, date: "March 19, 2022", venue: "Wells Fargo Center", city: "Philadelphia, PA" },
  { artist_id: 9, date: "February 25, 2022", venue: "Scotiabank Arena", city: "Toronto, Canada" },
  { artist_id: 9, date: "January 15, 2022", venue: "TD Garden", city: "Boston, MA" },
  { artist_id: 9, date: "December 10, 2021", venue: "United Center", city: "Chicago, IL" },
  { artist_id: 9, date: "November 5, 2021", venue: "Madison Square Garden", city: "New York, NY" },
  { artist_id: 9, date: "October 1, 2021", venue: "Red Rocks Amphitheatre", city: "Morrison, CO" },
  { artist_id: 9, date: "September 15, 2021", venue: "Hollywood Bowl", city: "Los Angeles, CA" },
  { artist_id: 9, date: "August 10, 2021", venue: "The O2", city: "London, England" },
  { artist_id: 9, date: "July 5, 2021", venue: "Olympia Theatre", city: "Dublin, Ireland" },

  { artist_id: 10, date: "March 19, 2022", venue: "Lollapalooza Argentina", city: "San Isidro, Argentina" },
  { artist_id: 10, date: "August 27, 2011", venue: "Reading Festival", city: "Reading, England" },
  { artist_id: 10, date: "July 15, 2022", venue: "The Roxy", city: "Los Angeles, CA" },
  { artist_id: 10, date: "June 20, 2022", venue: "Hollywood Bowl", city: "Los Angeles, CA" },
  { artist_id: 10, date: "May 18, 2022", venue: "Red Rocks Amphitheatre", city: "Morrison, CO" },
  { artist_id: 10, date: "April 25, 2022", venue: "Coachella", city: "Indio, CA" },
  { artist_id: 10, date: "March 15, 2022", venue: "Madison Square Garden", city: "New York, NY" },
  { artist_id: 10, date: "February 10, 2022", venue: "Barclays Center", city: "Brooklyn, NY" },
  { artist_id: 10, date: "January 22, 2022", venue: "The Forum", city: "Los Angeles, CA" },
  { artist_id: 10, date: "December 5, 2021", venue: "Scotiabank Arena", city: "Toronto, Canada" },

  { artist_id: 11, date: "December 7, 2024", venue: "3Arena", city: "Dublin, Ireland" },
  { artist_id: 11, date: "November 22, 2024", venue: "Alexandra Palace", city: "London, England" },
  { artist_id: 11, date: "October 10, 2024", venue: "Barrowland Ballroom", city: "Glasgow, Scotland" },
  { artist_id: 11, date: "September 18, 2024", venue: "O2 Academy", city: "Birmingham, England" },
  { artist_id: 11, date: "August 20, 2024", venue: "Royal Albert Hall", city: "London, England" },
  { artist_id: 11, date: "July 15, 2024", venue: "Olympia Theatre", city: "Dublin, Ireland" },
  { artist_id: 11, date: "June 25, 2024", venue: "The SSE Arena", city: "Belfast, Northern Ireland" },
  { artist_id: 11, date: "May 30, 2024", venue: "O2 Academy Brixton", city: "London, England" },
  { artist_id: 11, date: "April 22, 2024", venue: "First Direct Arena", city: "Leeds, England" },
  { artist_id: 11, date: "March 10, 2024", venue: "Manchester Arena", city: "Manchester, England" },
])
